### PR TITLE
Updated the invite link

### PR DESCRIPTION
**Pull request by Kyro3400**
Since the bot was nothing (i made i bot that i'm physically making so that's why it has a ID now)

### CODE REVIEW

**Comment by Jonfirexbox** [comment]
never mind

**Comment by Jonfirexbox** [comment]
never mind, im re-branding the bot, so just keep it the way it was

**Comment by Kyro3400** [comment]
Sorry to keep re-opening the PR

**Comment by Kyro3400** [comment]
OK! im just going to close this, but not delete my branch, so if mel wants to use this he can
also if @melmsie sees this and i don't reply, he should message me on discord: Jonfirexbox#3400

**Pull request closed without merging**
